services:
  retail-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: retail-app:${APP_VERSION:-4.2.0}
    container_name: retail-app
    ports:
      - "8081:8081"
    environment:
      APP_VERSION: ${APP_VERSION:-4.2.0}
      ENVIRONMENT: ${ENVIRONMENT:-UAT}
      PORT: 8081
    networks:
      - retail-network

networks:
  retail-network:
    name: retail-network